
name: Sync workflow

on:
  schedule:
    - cron: '0/5 * * * *' 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          user_email:  ${{ secrets.USER_EMAIL }}
          user_name:  ${{ secrets.USER_NAME }}
          token: ${{ github.token }}
      - run: |
          echo $USER_EMAIL
          echo $USER_NAME
          git config --global user.email $USER_EMAIL
          git config --global user.name $USER_NAME
          git remote add upstream $GITHUB_SERVER_URL/geored/test-sync-workflow.git
          git remote -v
          git fetch upstream
          git checkout main
          git merge --allow-unrelated-histories upstream/main
          git push --set-upstream origin main

