
name: Sync New workflow

on:
  schedule:
    - cron: '0/15 * * * *' 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git remote -v
          git remote add upstream $GITHUB_SERVER_URL/geored/test-sync-workflow.git
          git remote -v
          git fetch upstream
          git checkout main
          git merge  upstream/main
          git push --set-upstream origin main
